//HintName: MyEither`3.generated.cs
// <auto-generated />

#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Diagnostics.Contracts;
using System.Runtime.Serialization;
using System.Threading;
using System.Threading.Tasks;
using W4k.Either.Abstractions;

namespace MyLittleEither.MyLittleEitherMonad
{
    [Serializable]
    readonly partial struct MyEither<TLeft, TMiddle, TRight> : IEquatable<MyEither<TLeft, TMiddle, TRight>>, ISerializable
        where TLeft : notnull
        where TMiddle : notnull
        where TRight : notnull
    {
        private readonly byte _idx;
        private readonly TLeft? _v0;
        private readonly TMiddle? _v1;
        private readonly TRight? _v2;

        public MyEither(TLeft v0)
        {
            ThrowHelper.ThrowIfNull(v0);
            _idx = 0;
            _v0 = v0;
        }

        public MyEither(TMiddle v1)
        {
            ThrowHelper.ThrowIfNull(v1);
            _idx = 1;
            _v1 = v1;
        }

        public MyEither(TRight v2)
        {
            ThrowHelper.ThrowIfNull(v2);
            _idx = 2;
            _v2 = v2;
        }

        private MyEither(SerializationInfo info, StreamingContext context)
        {
            _idx = info.GetByte(nameof(_idx));
            switch (_idx)
            {
                case 0:
                    _v0 = (TLeft?)info.GetValue(nameof(_v0), typeof(TLeft));
                    break;
                case 1:
                    _v1 = (TMiddle?)info.GetValue(nameof(_v1), typeof(TMiddle));
                    break;
                case 2:
                    _v2 = (TRight?)info.GetValue(nameof(_v2), typeof(TRight));
                    break;
                default:
                    ThrowHelper.ThrowOnInvalidState();
                    break;
            }
        }

        [Pure]
        public object? Case
        {
            get
            {
                switch (_idx)
                {
                    case 0:
                        return _v0;
                    case 1:
                        return _v1;
                    case 2:
                        return _v2;
                    default:
                        return ThrowHelper.ThrowOnInvalidState<object?>();
                }
            }
        }

        [Pure]
        public static bool operator ==(MyEither<TLeft, TMiddle, TRight> left, MyEither<TLeft, TMiddle, TRight> right) => left.Equals(right);

        [Pure]
        public static bool operator !=(MyEither<TLeft, TMiddle, TRight> left, MyEither<TLeft, TMiddle, TRight> right) => !left.Equals(right);

        [Pure]
        public static implicit operator MyEither<TLeft, TMiddle, TRight>(TLeft v) => new(v);

        [Pure]
        public static implicit operator MyEither<TLeft, TMiddle, TRight>(TMiddle v) => new(v);

        [Pure]
        public static implicit operator MyEither<TLeft, TMiddle, TRight>(TRight v) => new(v);

        [Pure]
        public override int GetHashCode()
        {
            switch (_idx)
            {
                case 0:
                    return _v0?.GetHashCode() ?? 0;
                case 1:
                    return _v1?.GetHashCode() ?? 0;
                case 2:
                    return _v2?.GetHashCode() ?? 0;
                default:
                    return ThrowHelper.ThrowOnInvalidState<int>();
            }
        }

        [Pure]
        public override string ToString()
        {
            switch (_idx)
            {
                case 0:
                    return _v0?.ToString() ?? string.Empty;
                case 1:
                    return _v1?.ToString() ?? string.Empty;
                case 2:
                    return _v2?.ToString() ?? string.Empty;
                default:
                    return ThrowHelper.ThrowOnInvalidState<string>();
            }
        }

        [Pure]
        public override bool Equals(object? obj)
        {
            if (obj is not MyEither<TLeft, TMiddle, TRight> other)
            {
                return false;
            }

            return Equals(other);
        }

        [Pure]
        public bool Equals(MyEither<TLeft, TMiddle, TRight> other)
        {
            if (_idx != other._idx)
            {
                return false;
            }

            switch (_idx)
            {
                case 0:
                    return _v0!.Equals(other._v0);
                case 1:
                    return _v1!.Equals(other._v1);
                case 2:
                    return _v2!.Equals(other._v2);
                default:
                    return ThrowHelper.ThrowOnInvalidState<bool>();
            }
        }

        [Pure]
        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(_idx), _idx);
            switch (_idx)
            {
                case 0:
                    info.AddValue(nameof(_v0), _v0);
                    break;
                case 1:
                    info.AddValue(nameof(_v1), _v1);
                    break;
                case 2:
                    info.AddValue(nameof(_v2), _v2);
                    break;
                default:
                    ThrowHelper.ThrowOnInvalidState();
                    break;
            }
        }

        [Pure]
        public bool TryPick([NotNullWhen(true)] out TLeft? value)
        {
            if (_idx == 0)
            {
                value = _v0!;
                return true;
            }

            value = default;
            return false;
        }

        [Pure]
        public bool TryPick([NotNullWhen(true)] out TMiddle? value)
        {
            if (_idx == 1)
            {
                value = _v1!;
                return true;
            }

            value = default;
            return false;
        }

        [Pure]
        public bool TryPick([NotNullWhen(true)] out TRight? value)
        {
            if (_idx == 2)
            {
                value = _v2!;
                return true;
            }

            value = default;
            return false;
        }

        public TResult Match<TResult>(
            Func<TLeft, TResult> f0,
            Func<TMiddle, TResult> f1,
            Func<TRight, TResult> f2)
        {
            ThrowHelper.ThrowIfNull(f0);
            ThrowHelper.ThrowIfNull(f1);
            ThrowHelper.ThrowIfNull(f2);

            switch(_idx)
            {
                case 0:
                    return f0(_v0!);
                case 1:
                    return f1(_v1!);
                case 2:
                    return f2(_v2!);
                default:
                    return ThrowHelper.ThrowOnInvalidState<TResult>();
            };
        }

        public TResult Match<TState, TResult>(
            TState state,
            Func<TState, TLeft, TResult> f0,
            Func<TState, TMiddle, TResult> f1,
            Func<TState, TRight, TResult> f2)
        {
            ThrowHelper.ThrowIfNull(f0);
            ThrowHelper.ThrowIfNull(f1);
            ThrowHelper.ThrowIfNull(f2);

            switch(_idx)
            {
                case 0:
                    return f0(state, _v0!);
                case 1:
                    return f1(state, _v1!);
                case 2:
                    return f2(state, _v2!);
                default:
                    return ThrowHelper.ThrowOnInvalidState<TResult>();
            };
        }

        public Task<TResult> MatchAsync<TResult>(
            Func<TLeft, CancellationToken, Task<TResult>> f0,
            Func<TMiddle, CancellationToken, Task<TResult>> f1,
            Func<TRight, CancellationToken, Task<TResult>> f2,
            CancellationToken cancellationToken = default)
        {
            ThrowHelper.ThrowIfNull(f0);
            ThrowHelper.ThrowIfNull(f1);
            ThrowHelper.ThrowIfNull(f2);

            switch(_idx)
            {
                case 0:
                    return f0(_v0!, cancellationToken);
                case 1:
                    return f1(_v1!, cancellationToken);
                case 2:
                    return f2(_v2!, cancellationToken);
                default:
                    return ThrowHelper.ThrowOnInvalidState<Task<TResult>>();
            };
        }

        public Task<TResult> MatchAsync<TState, TResult>(
            TState state,
            Func<TState, TLeft, CancellationToken, Task<TResult>> f0,
            Func<TState, TMiddle, CancellationToken, Task<TResult>> f1,
            Func<TState, TRight, CancellationToken, Task<TResult>> f2,
            CancellationToken cancellationToken = default)
        {
            ThrowHelper.ThrowIfNull(f0);
            ThrowHelper.ThrowIfNull(f1);
            ThrowHelper.ThrowIfNull(f2);

            switch(_idx)
            {
                case 0:
                    return f0(state, _v0!, cancellationToken);
                case 1:
                    return f1(state, _v1!, cancellationToken);
                case 2:
                    return f2(state, _v2!, cancellationToken);
                default:
                    return ThrowHelper.ThrowOnInvalidState<Task<TResult>>();
            };
        }

        public void Switch(
            Action<TLeft> a0,
            Action<TMiddle> a1,
            Action<TRight> a2)
        {
            Match(
                v => { a0(v); return Unit.Default; },
                v => { a1(v); return Unit.Default; },
                v => { a2(v); return Unit.Default; });
        }

        public void Switch<TState>(
            TState state,
            Action<TState, TLeft> a0,
            Action<TState, TMiddle> a1,
            Action<TState, TRight> a2)
        {
            Match(
                state,
                (s, v) => { a0(s, v); return Unit.Default; },
                (s, v) => { a1(s, v); return Unit.Default; },
                (s, v) => { a2(s, v); return Unit.Default; });
        }

        public Task SwitchAsync(
            Func<TLeft, CancellationToken, Task> a0,
            Func<TMiddle, CancellationToken, Task> a1,
            Func<TRight, CancellationToken, Task> a2,
            CancellationToken cancellationToken = default)
        {
            return MatchAsync(
                async (v, ct) => { await a0(v, ct); return Unit.Default; },
                async (v, ct) => { await a1(v, ct); return Unit.Default; },
                async (v, ct) => { await a2(v, ct); return Unit.Default; },
                cancellationToken);
        }

        public Task SwitchAsync<TState>(
            TState state,
            Func<TState, TLeft, CancellationToken, Task> a0,
            Func<TState, TMiddle, CancellationToken, Task> a1,
            Func<TState, TRight, CancellationToken, Task> a2,
            CancellationToken cancellationToken = default)
        {
            return MatchAsync(
                state,
                async (s, v, ct) => { await a0(s, v, ct); return Unit.Default; },
                async (s, v, ct) => { await a1(s, v, ct); return Unit.Default; },
                async (s, v, ct) => { await a2(s, v, ct); return Unit.Default; },
                cancellationToken);
        }
    }
}
